### ISSUE TITLE
ToDo list for `v2.0.0` release

### ISSUE THREAD

**Issue by trappitsch** [RIMS-Code/RIMSEval#44]
The following are the necessary additions to the software that need to be made before releasing `v2.0.0`.

- [x] Full test suite that includes complete line coverage (#43)
- [x] Debug (if necessary) / test further the "cut spectrum" functionality (#45)
- [x] Improve tests for Peirce criterion (#46)
- [x] Check dependencies and ensure that we run the latest `numba` (#47)
- [x] Update docs (#49)

**Comment by trappitsch** [comment]
Complete line coverage is achieved for all critical functions. Peirce criterion filter has incomplete coverage / testing, but also raises a user warning to state this!

**Comment by trappitsch** [comment]
"Cut Spectrum" functions allowed for funky starting indexes. The array is intenionally 1 indexed. However, when the user entered 0 or -1 as the starting index, they could end up with more shots that are in the file. The index range is now checked for (#45). 

Testing with multiple files did not yield any other issues. Anything else that comes to your mind @msavina1 @DZS2020 ?

**Comment by trappitsch** [comment]
No bug comments on the cut spectrum or other features, even after asking people.
